### ISSUE TITLE
Search Results does not populate

### ISSUE THREAD

**Issue by picks6** [KBailey-95/speed-run-spectator#9]
The Search Results div should populate with the name year and top 3 runs for the most popular categories

For reference: https://www.speedrun.com/supermetroid

A Games Search for Super Metroid should return
Super Metroid - 1994
The top 3 any% runs (https://www.speedrun.com/api/v1/categories/9d8v96lk/records)

**Comment by PatrickFHam** [comment]
The dirty-work on this is done, but I'm seeing now we'll need to adjust it... I had built it on a user's name search, rather than a game search.  Woops.

Search results work great, when called manually... I still can't get the stupid thing to call automatically, at the end of the bigger function.  Driving me nuts.

**Comment by picks6** [comment]
I built a second function called awaitResults which stalls until displayResults is ready. Not the cleanest solution, but its working.
